name: ci_cd_pipeline_development.yml
on:
  schedule:
    - cron: '30 13 * * 1,2,3,4,5'
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  ## Cloudhub Properties
  CLOUDHUB_WORKERS: 2
  CLOUDHUB_WORKER_TYPE: MICRO
  CLOUDHUB_REGION: us-east-01  

  ## API specific 
  HTTP_PRIVATE_PORT: 8091  

jobs:
  build_deploy_dev-01:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_ENVIRONMENT: "dev-01"
      GITHUB_ENVIRONMENT: "dev"      
      CLOUDHUB_WORKERS: "1"
      CLOUDHUB_WORKER_TYPE: "MICRO"
      CLOUDHUB_REGION: "ca-central-1"
      HTTP_PRIVATE_PORT: "8091"
    secrets:
      CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}        
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}


  build_deploy_qa-01:
    needs: [build_deploy_dev-01]
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_ENVIRONMENT: "qa-01"
      GITHUB_ENVIRONMENT: "dev"      
      CLOUDHUB_WORKERS: "1"
      CLOUDHUB_WORKER_TYPE: "MICRO"
      CLOUDHUB_REGION: "ca-central-1"
      HTTP_PRIVATE_PORT: "8091"
    secrets:
      CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}    
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}
